name: Node.js Package

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build  # Assuming you have a "build" script in your package.json

      - name: Publish to GitHub Packages
        run: |
          if [ -n "$GITHUB_TOKEN" ]; then
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
          fi
          npm publish
