name: Node.js Package

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set working directory
        run: cd sample-packages/npm  # Set the correct path to your project
        shell: bash

      - name: Validate package.json
        run: npm ls --json
        working-directory: sample-packages/npm  # Set the correct path to your project

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: sample-packages/npm  # Set the correct path to your project

      - name: Run tests
        run: npm test
        working-directory: sample-packages/npm  # Set the correct path to your project

      - name: Build
        run: npm run build  # Assuming you have a "build" script in your package.json
        working-directory: sample-packages/npm  # Set the correct path to your project

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc

      - name: Publish to GitHub Packages
        run: npm publish
        working-directory: sample-packages/npm  # Set the correct path to your project
